const defaultData = {
	technology: [
		{
			source: {
				id: "google-news",
				name: "Google News",
			},
			author: "Kotaku",
			title: "Diablo IV Glitch Lets Player Gain 30+ Levels In One Second - Kotaku",
			description: null,
			url: "https://news.google.com/rss/articles/CBMiiwFBVV95cUxQZnB6dHJLajJQUjYyMzZNdVVhY1gycmtfeWU5N2ItUHNERUhaeTRCVk9vUVZTZ1BEMVdUNnRXVWF1VjYzSUpZVjZEZHRkbXNjZ1V2Wkdkb0NzQ01XZnNhRmFETjZnZXpac0hKMzFYOVNNaWVwUVFyN1VnLUhLcEN0VHFTaXp2MUpwRzJV?oc=5",
			urlToImage: null,
			publishedAt: "2024-08-07T21:40:00Z",
			content: null,
		},
		{
			source: {
				id: "google-news",
				name: "Google News",
			},
			author: "IGN",
			title: "Suicide Squad: Kill the Justice League Spurs Double-Digit Drop in WB Gaming Revenue - IGN",
			description: null,
			url: "https://news.google.com/rss/articles/CBMisAFBVV95cUxPNzl1QzlDTEhFMkxITlJ3OEJoSXYyaEVoUndzX1pUdFVOTVdiS0dBTXV4eUhiUlZoRzRuVWVUQnhNczJLQW1LNmRidjNPaU1ZQlc0NHM1QXdYc2c0NEUxak4zNElkandzNGMteGVkaXdMYS1aYnl0TlVXTnhQVkpNbU15SXFzWEVIelpKeXJYRzdkTXVkaUlCaXNFRndzVDdYTkYwM0JQZ1VSd0ZDY29Udw?oc=5",
			urlToImage: null,
			publishedAt: "2024-08-07T21:11:28Z",
			content: null,
		},
		{
			source: {
				id: "google-news",
				name: "Google News",
			},
			author: "The Verge",
			title: "Sonos delays two new products as it races to fix buggy app - The Verge",
			description: null,
			url: "https://news.google.com/rss/articles/CBMikwFBVV95cUxPbHlSUDJqYjhrWmpnWHlxbjFpM0k3MlNRWTRLOFVkMEV4ZU42YlZmYTkzZXRyS2tmeDk5UHd4R3ExVFpMNDhnUFVhek13TVpsU19seXp4SU1IWXlxMDVqWEF1N09CaHpJbnJjTzlaZzBTMHhLRjlBd0FOZWRhcm5uQ2RHZTcwNXN6VDk3bmNQdUwwNk0?oc=5",
			urlToImage: null,
			publishedAt: "2024-08-07T20:33:13Z",
			content: null,
		},
		{
			source: {
				id: "google-news",
				name: "Google News",
			},
			author: "9to5Google",
			title: "The Google TV Streamer still supports external storage - 9to5Google",
			description: null,
			url: "https://news.google.com/rss/articles/CBMiekFVX3lxTE9TclZOcFVVZGdUcW9zNHQ0ZzltUVpGbFFIaEdfREo4b2FGbG5vcmQ4MFZEc0dpYWFRZmF6RUlfRkY4dUpxSXJDcXpOa3NqU3U5aFFjYWtNOTNXeVBtNGdyc1liTXlFTkxncmVSV3JXWmZ0TGhuMVFVbVd3?oc=5",
			urlToImage: null,
			publishedAt: "2024-08-07T20:30:00Z",
			content: null,
		},
		{
			source: {
				id: "google-news",
				name: "Google News",
			},
			author: "BleepingComputer",
			title: 'Windows Update downgrade attack "unpatches" fully-updated systems - BleepingComputer',
			description: null,
			url: "https://news.google.com/rss/articles/CBMisgFBVV95cUxNMXhhTDg2SGVmOHJDZjNkdHZFYVp2QnlnS1RrT1lUcjlnZWZrZEFkclAwdzQ2M1FYUGhaZ3dZbXYwVmxZdC0xNVJHMDF2TG5UdkZGX1pWVDF6N3ZmeWhjZnFNbE9oUmhEc25idW5wSTF3S3BQRXNiX2NlR2YxNlJJWUE0cXpralJ5Y3lnNE1DMlNsS1phdXYtVExfcjhSNTNSbXlObmFnT1VyLUFKSnRIa09B0gG3AUFVX3lxTE1qWXJybGM3QXhkTFFZM1NJczRBTkNVaXZXY3hhWGFWMEQ4TUs3c1dRNkF0S0YxLWJyY1ItRFdZVU96QUl0aE5URkZTamsyTjdxaGNxT0tiS2FneVN2NG9ZVzBIMFlFNEk0UUl0dlpvMlhHV0plYTJmQWhWNXVWTk9rNTBtWGgzcjZxb2pkZUZXTGFiS096Vzl1bzExbTVNVlk0TzNNaG9CN3VBRlA5Umh5N1d5TEZ1cw?oc=5",
			urlToImage: null,
			publishedAt: "2024-08-07T20:24:33Z",
			content: null,
		},
		{
			source: {
				id: "google-news",
				name: "Google News",
			},
			author: "9to5Toys",
			title: "Big-time M3 MacBook Air deals still flying! 13-inch $149 off from $850, 15-inch 16GB $249 off - 9to5Toys",
			description: null,
			url: "https://news.google.com/rss/articles/CBMihgFBVV95cUxNZGJfMUt4Uk1xV3NVcGs4NzE0NzZxd00xMVFDeXdIRUlTd0E2b3pwam5KSks3SDNlb0VUdGNyVllGM08wMklpSW9aaE5ITjJZTFIxZGFuTkprNlNlMlFSTEtYN2FGeUM0b2tvcUNIYTBIZkJRNVBEalRyS1NMNk0xeUt5WUVRd9IBhgFBVV95cUxNZGJfMUt4Uk1xV3NVcGs4NzE0NzZxd00xMVFDeXdIRUlTd0E2b3pwam5KSks3SDNlb0VUdGNyVllGM08wMklpSW9aaE5ITjJZTFIxZGFuTkprNlNlMlFSTEtYN2FGeUM0b2tvcUNIYTBIZkJRNVBEalRyS1NMNk0xeUt5WUVRdw?oc=5",
			urlToImage: null,
			publishedAt: "2024-08-07T19:55:25Z",
			content: null,
		},
		{
			source: {
				id: "google-news",
				name: "Google News",
			},
			author: "Engadget",
			title: "People are returning Humane AI Pins faster than the company can sell them - Engadget",
			description: null,
			url: "https://news.google.com/rss/articles/CBMitwFBVV95cUxNY1JITG0xVFVCVXVoLUwzbERUNmFmaEtCRmRKVTZ0OFJmWFBWcXFoMk1Xb2N6Q2xrS0daZWxiT3dEaEtKTlJVanVTVEdtdVNiVWxONFhfLXlXSFZabjBtZ2RZOEJ5WHlKc2ZIZXJPQl9sNHgtOWlKaWtMVFhqMl9CdFVDeWJYQ015dDl0TVJtYk04YzROUGNwejEycVcwXzZLREVtOW16WnF6WjgtLW5COTJra0RoZ0k?oc=5",
			urlToImage: null,
			publishedAt: "2024-08-07T19:15:23Z",
			content: null,
		},
		{
			source: {
				id: "google-news",
				name: "Google News",
			},
			author: "TechCrunch",
			title: "Made by Google 2024: How to watch Google unveil the Pixel 9, a new foldable and more - TechCrunch",
			description: null,
			url: "https://news.google.com/rss/articles/CBMiuAFBVV95cUxQYnUzQ1lndGlwUjNvYzZnb1NFMGl0aHg0QUxITWIyWDlydUp1VGdfOGNOQkJDbXRVY0MzNDVwNHo2clZXdEFzWUNHSzVlalZETjd0SGRyTnpVcmxKLVVsN1pJUHg1QXNfdHZ6TlJPN25kaTM5OXFmaXdEYlQxX29xNTJJVWptR0NCalZhenZiUjRRUWI4VDVJVURUektOcUR4cXBEUUNPOFZ4S013SzhZUllCclU3cDNW?oc=5",
			urlToImage: null,
			publishedAt: "2024-08-07T19:10:25Z",
			content: null,
		},
		{
			source: {
				id: "google-news",
				name: "Google News",
			},
			author: "The Verge",
			title: "Fortnite will bring battle pass rewards back around - The Verge",
			description: null,
			url: "https://news.google.com/rss/articles/CBMimAFBVV95cUxNZWx1MGZmbTFuU05MQUs5U3ZYdFZCVzIzUHo5ZXFqNzZOenVwNFJicllxb1pNR0t4S3ZoNVFnOFpFZ2s2Vm9qMWExQVh5aW1KVHdKMW1sWWlqT1F4am9pZ1NoQms1aW1lcWhVdWNmeGNfbloycFJPR1RHQWg5aUdxanlxNmtId2hoVDZTYkxTU1ZQd1NkZGo5dA?oc=5",
			urlToImage: null,
			publishedAt: "2024-08-07T19:03:48Z",
			content: null,
		},
		{
			source: {
				id: "google-news",
				name: "Google News",
			},
			author: "CNET",
			title: "Nab the Anker Prime 250W USB-C Charging Station for $30 at Amazon Right Now - CNET",
			description: null,
			url: "https://news.google.com/rss/articles/CBMipAFBVV95cUxOcHEyQ1hjLWZOM2dJWi04NzBkVzNKRm1mMmJDMHpJVUZVSV93REFNWTh4STE5aUF5NFdOcl9aUzVqbnFlUGtrY3JtaFVUOVhKenNHNkx3YTZRNkh1bEZJZW9fVGpiNGRNNG10OXl6RHNuVkZGeGJ5Q0RJYkJQc1dQTFozVFN2VlFuTlc5WlAzMHhoSFhIUlY2cng3dlJNVDFJYkR4Qg?oc=5",
			urlToImage: null,
			publishedAt: "2024-08-07T19:01:00Z",
			content: null,
		},
		{
			source: {
				id: "google-news",
				name: "Google News",
			},
			author: "Android Central",
			title: "Meta is closing a beloved first-party Quest studio - Android Central",
			description: null,
			url: "https://news.google.com/rss/articles/CBMiiwFBVV95cUxPZTNPckdrV3EtQkNtT25MTlV1UnRSN0N0WWFST242QVA1WTVpUTB4LVF1N1dydkFGMTFNNWNaTG5RdnVPWVNaRXNGUDJHQlZuNVpHNWJsdWpuZzJhOTZfWDVJVGxLYWNvdThYYlZoRUtGVE1qNFMwMmNNZmZsWWlnWTVnenNnNWpmTWY0?oc=5",
			urlToImage: null,
			publishedAt: "2024-08-07T18:15:03Z",
			content: null,
		},
		{
			source: {
				id: "google-news",
				name: "Google News",
			},
			author: "The Washington Post",
			title: "Think you are sick? It may be the nocebo effect. - The Washington Post",
			description: null,
			url: "https://news.google.com/rss/articles/CBMilgFBVV95cUxPUmF1NVZmZnUzQkhndS1sN09NRXFJNWY3MXJncFNJcExUSmZkUFBBQjZPejN0UWpHVE4wNTJGOHRQd3lVRS1RTUZxc283X28xWndqOWZIX0R3WUJkM0JLczR5WllFT3hJY1RGc01iR3NkLVhzZ0J5RG9sV05XOVY5R0l3YkRXeFR1bXN2dlFsa0h4SDh1VUE?oc=5",
			urlToImage: null,
			publishedAt: "2024-08-07T18:00:00Z",
			content: null,
		},
		{
			source: {
				id: "google-news",
				name: "Google News",
			},
			author: "9to5Mac",
			title: "Apple releases iOS 17.6.1 for iPhone with ‘important bug fixes’ - 9to5Mac",
			description: null,
			url: "https://news.google.com/rss/articles/CBMie0FVX3lxTE8zZkxmSnJ6M1Z1ZFNGa3JJRGRiRGFjSlRuWVFZb3dqMVYtRnJOcExQNVZVSFp4dTB0cXlZRG9FdDMtdHFOWXk4SG5aV1FqOU83UmlRdEc3dkYtZlBMTVdEWnZSdDlaRU1WT05VZ2ZqeWpsVzVtRmFKZUtUQQ?oc=5",
			urlToImage: null,
			publishedAt: "2024-08-07T17:35:00Z",
			content: null,
		},
		{
			source: {
				id: "google-news",
				name: "Google News",
			},
			author: "Nintendo Life",
			title: "Review: Natsu-Mon: 20th Century Summer Kid (Switch) - A Pleasant Vacation, If You're Patient - Nintendo Life",
			description: null,
			url: "https://news.google.com/rss/articles/CBMiiwFBVV95cUxNWG5hQTNuXzlsLWQzcFpkd25qcExfUHhCMVkxUlRDUnlOS045ZFM0Qmt2VDBMVm5UNDJUa3pQNlgyakx5NDVsMlBaelBaM1ptYkFYYWQ5ZzF2aDRYSXh0LW85ZWpPcC1PNjZYN25kdGZKVHlqTmpNRFFyYUhhd2dQLW40NnZPRkRkVThJ?oc=5",
			urlToImage: null,
			publishedAt: "2024-08-07T17:00:00Z",
			content: null,
		},
		{
			source: {
				id: "google-news",
				name: "Google News",
			},
			author: "Ars Technica",
			title: "Report: Apple’s external DVD drive is up burning discs in dongle heaven - Ars Technica",
			description: null,
			url: "https://news.google.com/rss/articles/CBMiqgFBVV95cUxOVUhPWThFRndORE5Fc3NaZlV4ekgzdFpYQVdBb0xFYzlMV0I5VUY5VGl0Z0Y1TTU2UExLTGh2UmRRVHVfMEhrVVN0enFpNW9Vckd6b3FrZV9icDhpemRpM2ZvVExOcXBHZ19icGFmZzd0MnRNZkVpXzJMd1QwS1lraHVHRnZnMHZlY1J2NENBQW9TSWtENUw4UDNySGxEV0c1R3VsYmxHYWt3QQ?oc=5",
			urlToImage: null,
			publishedAt: "2024-08-07T16:56:59Z",
			content: null,
		},
		{
			source: {
				id: "google-news",
				name: "Google News",
			},
			author: "Engadget",
			title: "Balatro is getting its first big, free gameplay update in 2025 - Engadget",
			description: null,
			url: "https://news.google.com/rss/articles/CBMirAFBVV95cUxQdS1SVXRUbV9Bc3RYc3lrc2R2WnZHQkM4bWJ3SHkxUlNJX2puSXVTTWNaT05NZkNmU3dIZjEzTkZqLVB4Y1pLUlJWOVJYdVhva2RvanI1VjE2Mktna0dXY0YtZDlXMkpZTkMyQUZObW5sU0NFTGxsSkd6cEZCWnlObFlrNlBmNllBbG96SmxkLUE2bWZVelhvV0dULU10d1ZxTlNwdFhQcHcwbGNJ?oc=5",
			urlToImage: null,
			publishedAt: "2024-08-07T16:19:38Z",
			content: null,
		},
		{
			source: {
				id: "google-news",
				name: "Google News",
			},
			author: "GameSpot",
			title: "Warhammer 40k: Space Marine 2 - All Classes PvE Co-Op Gameplay - GameSpot",
			description: null,
			url: "https://news.google.com/rss/articles/CCAiC3FiWXQtRHFlbUZZmAEB?oc=5",
			urlToImage: null,
			publishedAt: "2024-08-07T16:00:53Z",
			content: null,
		},
		{
			source: {
				id: "google-news",
				name: "Google News",
			},
			author: "EventHubs",
			title: "Terry Bogard demo and trailer confirmed coming later this month for Street Fighter 6 and here's when the party starts - EventHubs",
			description: null,
			url: "https://news.google.com/rss/articles/CBMifkFVX3lxTFBobXpOMkVmdkw4eXlxcGo5UHNwTS1mMUhWdmxUbWFMYVVsY0poWkZ2dUlUeGRvSWZCWHoxVDQ5MDFUZlBZa2dYZkpFb2Qyd0lFbzRfWXZNNHVVSWtHT0VKU2dFNTFnejE5Qkd6Wi1neDAwbmx6RV9EQndYNFZwdw?oc=5",
			urlToImage: null,
			publishedAt: "2024-08-07T15:40:38Z",
			content: null,
		},
		{
			source: {
				id: "google-news",
				name: "Google News",
			},
			author: "Forbes",
			title: "‘Helldivers 2’s Big Update Draws Negative Reviews, Doesn’t Quite Double Playercount - Forbes",
			description: null,
			url: "https://news.google.com/rss/articles/CBMiygFBVV95cUxQNFNheTBieUxmNEJZa0pIZ1NrVTlBUDhJVFJ1R1Z3eVRsQXltV2NIdkIxc0ptR21BMlNkYU5wczVkRGQzbHdxa0NHc0J3VERpV3VZb29NZ3F0N1c4NkItZWYzaWozdXFCaC1Bd2EtZWxxRjNXeDZWM3lXay1OamxmcGphSEFDYnhxeG4walNDZ3dKWHNlaC0ySzREaWZ6Tk96OHFjYnVLeE4zVnpBemtJMnhJYUhQVVpaTl9qazFxT0xCMlhYUDhXcVRR?oc=5",
			urlToImage: null,
			publishedAt: "2024-08-07T15:34:27Z",
			content: null,
		},
		{
			source: {
				id: "google-news",
				name: "Google News",
			},
			author: "Gizmodo",
			title: "Baldur's Gate 3's Latest Player Stats Reveal Who My Fellow Sickos Are - Gizmodo",
			description: null,
			url: "https://news.google.com/rss/articles/CBMilgFBVV95cUxPa2ExUFhBa0N6X285aWEtSEN4ejd4MXlhNUo1am1UZVVCdm44b0RjYW1TUmVWS1FEc1oyOUtkZzdVczVvOUxfZmczTHFtX2JBMEwzczNtazFBRDVxdlRtUDFIRnhYNWlnTlFJX0ZwVjd1MGVhdEVKdTBEZUtNUUtpT1o2SFJzcnhIZ2hfbFUySUk2enFDaWc?oc=5",
			urlToImage: null,
			publishedAt: "2024-08-07T15:32:17Z",
			content: null,
		},
	],
	sports: [
		{
			source: {
				id: "google-news",
				name: "Google News",
			},
			author: "Kotaku",
			title: "Diablo IV Glitch Lets Player Gain 30+ Levels In One Second - Kotaku",
			description: null,
			url: "https://news.google.com/rss/articles/CBMiiwFBVV95cUxQZnB6dHJLajJQUjYyMzZNdVVhY1gycmtfeWU5N2ItUHNERUhaeTRCVk9vUVZTZ1BEMVdUNnRXVWF1VjYzSUpZVjZEZHRkbXNjZ1V2Wkdkb0NzQ01XZnNhRmFETjZnZXpac0hKMzFYOVNNaWVwUVFyN1VnLUhLcEN0VHFTaXp2MUpwRzJV?oc=5",
			urlToImage: null,
			publishedAt: "2024-08-07T21:40:00Z",
			content: null,
		},
		{
			source: {
				id: "google-news",
				name: "Google News",
			},
			author: "IGN",
			title: "Suicide Squad: Kill the Justice League Spurs Double-Digit Drop in WB Gaming Revenue - IGN",
			description: null,
			url: "https://news.google.com/rss/articles/CBMisAFBVV95cUxPNzl1QzlDTEhFMkxITlJ3OEJoSXYyaEVoUndzX1pUdFVOTVdiS0dBTXV4eUhiUlZoRzRuVWVUQnhNczJLQW1LNmRidjNPaU1ZQlc0NHM1QXdYc2c0NEUxak4zNElkandzNGMteGVkaXdMYS1aYnl0TlVXTnhQVkpNbU15SXFzWEVIelpKeXJYRzdkTXVkaUlCaXNFRndzVDdYTkYwM0JQZ1VSd0ZDY29Udw?oc=5",
			urlToImage: null,
			publishedAt: "2024-08-07T21:11:28Z",
			content: null,
		},
		{
			source: {
				id: "google-news",
				name: "Google News",
			},
			author: "The Verge",
			title: "Sonos delays two new products as it races to fix buggy app - The Verge",
			description: null,
			url: "https://news.google.com/rss/articles/CBMikwFBVV95cUxPbHlSUDJqYjhrWmpnWHlxbjFpM0k3MlNRWTRLOFVkMEV4ZU42YlZmYTkzZXRyS2tmeDk5UHd4R3ExVFpMNDhnUFVhek13TVpsU19seXp4SU1IWXlxMDVqWEF1N09CaHpJbnJjTzlaZzBTMHhLRjlBd0FOZWRhcm5uQ2RHZTcwNXN6VDk3bmNQdUwwNk0?oc=5",
			urlToImage: null,
			publishedAt: "2024-08-07T20:33:13Z",
			content: null,
		},
		{
			source: {
				id: "google-news",
				name: "Google News",
			},
			author: "9to5Google",
			title: "The Google TV Streamer still supports external storage - 9to5Google",
			description: null,
			url: "https://news.google.com/rss/articles/CBMiekFVX3lxTE9TclZOcFVVZGdUcW9zNHQ0ZzltUVpGbFFIaEdfREo4b2FGbG5vcmQ4MFZEc0dpYWFRZmF6RUlfRkY4dUpxSXJDcXpOa3NqU3U5aFFjYWtNOTNXeVBtNGdyc1liTXlFTkxncmVSV3JXWmZ0TGhuMVFVbVd3?oc=5",
			urlToImage: null,
			publishedAt: "2024-08-07T20:30:00Z",
			content: null,
		},
		{
			source: {
				id: "google-news",
				name: "Google News",
			},
			author: "BleepingComputer",
			title: 'Windows Update downgrade attack "unpatches" fully-updated systems - BleepingComputer',
			description: null,
			url: "https://news.google.com/rss/articles/CBMisgFBVV95cUxNMXhhTDg2SGVmOHJDZjNkdHZFYVp2QnlnS1RrT1lUcjlnZWZrZEFkclAwdzQ2M1FYUGhaZ3dZbXYwVmxZdC0xNVJHMDF2TG5UdkZGX1pWVDF6N3ZmeWhjZnFNbE9oUmhEc25idW5wSTF3S3BQRXNiX2NlR2YxNlJJWUE0cXpralJ5Y3lnNE1DMlNsS1phdXYtVExfcjhSNTNSbXlObmFnT1VyLUFKSnRIa09B0gG3AUFVX3lxTE1qWXJybGM3QXhkTFFZM1NJczRBTkNVaXZXY3hhWGFWMEQ4TUs3c1dRNkF0S0YxLWJyY1ItRFdZVU96QUl0aE5URkZTamsyTjdxaGNxT0tiS2FneVN2NG9ZVzBIMFlFNEk0UUl0dlpvMlhHV0plYTJmQWhWNXVWTk9rNTBtWGgzcjZxb2pkZUZXTGFiS096Vzl1bzExbTVNVlk0TzNNaG9CN3VBRlA5Umh5N1d5TEZ1cw?oc=5",
			urlToImage: null,
			publishedAt: "2024-08-07T20:24:33Z",
			content: null,
		},
		{
			source: {
				id: "google-news",
				name: "Google News",
			},
			author: "9to5Toys",
			title: "Big-time M3 MacBook Air deals still flying! 13-inch $149 off from $850, 15-inch 16GB $249 off - 9to5Toys",
			description: null,
			url: "https://news.google.com/rss/articles/CBMihgFBVV95cUxNZGJfMUt4Uk1xV3NVcGs4NzE0NzZxd00xMVFDeXdIRUlTd0E2b3pwam5KSks3SDNlb0VUdGNyVllGM08wMklpSW9aaE5ITjJZTFIxZGFuTkprNlNlMlFSTEtYN2FGeUM0b2tvcUNIYTBIZkJRNVBEalRyS1NMNk0xeUt5WUVRd9IBhgFBVV95cUxNZGJfMUt4Uk1xV3NVcGs4NzE0NzZxd00xMVFDeXdIRUlTd0E2b3pwam5KSks3SDNlb0VUdGNyVllGM08wMklpSW9aaE5ITjJZTFIxZGFuTkprNlNlMlFSTEtYN2FGeUM0b2tvcUNIYTBIZkJRNVBEalRyS1NMNk0xeUt5WUVRdw?oc=5",
			urlToImage: null,
			publishedAt: "2024-08-07T19:55:25Z",
			content: null,
		},
		{
			source: {
				id: "google-news",
				name: "Google News",
			},
			author: "Engadget",
			title: "People are returning Humane AI Pins faster than the company can sell them - Engadget",
			description: null,
			url: "https://news.google.com/rss/articles/CBMitwFBVV95cUxNY1JITG0xVFVCVXVoLUwzbERUNmFmaEtCRmRKVTZ0OFJmWFBWcXFoMk1Xb2N6Q2xrS0daZWxiT3dEaEtKTlJVanVTVEdtdVNiVWxONFhfLXlXSFZabjBtZ2RZOEJ5WHlKc2ZIZXJPQl9sNHgtOWlKaWtMVFhqMl9CdFVDeWJYQ015dDl0TVJtYk04YzROUGNwejEycVcwXzZLREVtOW16WnF6WjgtLW5COTJra0RoZ0k?oc=5",
			urlToImage: null,
			publishedAt: "2024-08-07T19:15:23Z",
			content: null,
		},
		{
			source: {
				id: "google-news",
				name: "Google News",
			},
			author: "TechCrunch",
			title: "Made by Google 2024: How to watch Google unveil the Pixel 9, a new foldable and more - TechCrunch",
			description: null,
			url: "https://news.google.com/rss/articles/CBMiuAFBVV95cUxQYnUzQ1lndGlwUjNvYzZnb1NFMGl0aHg0QUxITWIyWDlydUp1VGdfOGNOQkJDbXRVY0MzNDVwNHo2clZXdEFzWUNHSzVlalZETjd0SGRyTnpVcmxKLVVsN1pJUHg1QXNfdHZ6TlJPN25kaTM5OXFmaXdEYlQxX29xNTJJVWptR0NCalZhenZiUjRRUWI4VDVJVURUektOcUR4cXBEUUNPOFZ4S013SzhZUllCclU3cDNW?oc=5",
			urlToImage: null,
			publishedAt: "2024-08-07T19:10:25Z",
			content: null,
		},
		{
			source: {
				id: "google-news",
				name: "Google News",
			},
			author: "The Verge",
			title: "Fortnite will bring battle pass rewards back around - The Verge",
			description: null,
			url: "https://news.google.com/rss/articles/CBMimAFBVV95cUxNZWx1MGZmbTFuU05MQUs5U3ZYdFZCVzIzUHo5ZXFqNzZOenVwNFJicllxb1pNR0t4S3ZoNVFnOFpFZ2s2Vm9qMWExQVh5aW1KVHdKMW1sWWlqT1F4am9pZ1NoQms1aW1lcWhVdWNmeGNfbloycFJPR1RHQWg5aUdxanlxNmtId2hoVDZTYkxTU1ZQd1NkZGo5dA?oc=5",
			urlToImage: null,
			publishedAt: "2024-08-07T19:03:48Z",
			content: null,
		},
		{
			source: {
				id: "google-news",
				name: "Google News",
			},
			author: "CNET",
			title: "Nab the Anker Prime 250W USB-C Charging Station for $30 at Amazon Right Now - CNET",
			description: null,
			url: "https://news.google.com/rss/articles/CBMipAFBVV95cUxOcHEyQ1hjLWZOM2dJWi04NzBkVzNKRm1mMmJDMHpJVUZVSV93REFNWTh4STE5aUF5NFdOcl9aUzVqbnFlUGtrY3JtaFVUOVhKenNHNkx3YTZRNkh1bEZJZW9fVGpiNGRNNG10OXl6RHNuVkZGeGJ5Q0RJYkJQc1dQTFozVFN2VlFuTlc5WlAzMHhoSFhIUlY2cng3dlJNVDFJYkR4Qg?oc=5",
			urlToImage: null,
			publishedAt: "2024-08-07T19:01:00Z",
			content: null,
		},
		{
			source: {
				id: "google-news",
				name: "Google News",
			},
			author: "Android Central",
			title: "Meta is closing a beloved first-party Quest studio - Android Central",
			description: null,
			url: "https://news.google.com/rss/articles/CBMiiwFBVV95cUxPZTNPckdrV3EtQkNtT25MTlV1UnRSN0N0WWFST242QVA1WTVpUTB4LVF1N1dydkFGMTFNNWNaTG5RdnVPWVNaRXNGUDJHQlZuNVpHNWJsdWpuZzJhOTZfWDVJVGxLYWNvdThYYlZoRUtGVE1qNFMwMmNNZmZsWWlnWTVnenNnNWpmTWY0?oc=5",
			urlToImage: null,
			publishedAt: "2024-08-07T18:15:03Z",
			content: null,
		},
		{
			source: {
				id: "google-news",
				name: "Google News",
			},
			author: "The Washington Post",
			title: "Think you are sick? It may be the nocebo effect. - The Washington Post",
			description: null,
			url: "https://news.google.com/rss/articles/CBMilgFBVV95cUxPUmF1NVZmZnUzQkhndS1sN09NRXFJNWY3MXJncFNJcExUSmZkUFBBQjZPejN0UWpHVE4wNTJGOHRQd3lVRS1RTUZxc283X28xWndqOWZIX0R3WUJkM0JLczR5WllFT3hJY1RGc01iR3NkLVhzZ0J5RG9sV05XOVY5R0l3YkRXeFR1bXN2dlFsa0h4SDh1VUE?oc=5",
			urlToImage: null,
			publishedAt: "2024-08-07T18:00:00Z",
			content: null,
		},
		{
			source: {
				id: "google-news",
				name: "Google News",
			},
			author: "9to5Mac",
			title: "Apple releases iOS 17.6.1 for iPhone with ‘important bug fixes’ - 9to5Mac",
			description: null,
			url: "https://news.google.com/rss/articles/CBMie0FVX3lxTE8zZkxmSnJ6M1Z1ZFNGa3JJRGRiRGFjSlRuWVFZb3dqMVYtRnJOcExQNVZVSFp4dTB0cXlZRG9FdDMtdHFOWXk4SG5aV1FqOU83UmlRdEc3dkYtZlBMTVdEWnZSdDlaRU1WT05VZ2ZqeWpsVzVtRmFKZUtUQQ?oc=5",
			urlToImage: null,
			publishedAt: "2024-08-07T17:35:00Z",
			content: null,
		},
		{
			source: {
				id: "google-news",
				name: "Google News",
			},
			author: "Nintendo Life",
			title: "Review: Natsu-Mon: 20th Century Summer Kid (Switch) - A Pleasant Vacation, If You're Patient - Nintendo Life",
			description: null,
			url: "https://news.google.com/rss/articles/CBMiiwFBVV95cUxNWG5hQTNuXzlsLWQzcFpkd25qcExfUHhCMVkxUlRDUnlOS045ZFM0Qmt2VDBMVm5UNDJUa3pQNlgyakx5NDVsMlBaelBaM1ptYkFYYWQ5ZzF2aDRYSXh0LW85ZWpPcC1PNjZYN25kdGZKVHlqTmpNRFFyYUhhd2dQLW40NnZPRkRkVThJ?oc=5",
			urlToImage: null,
			publishedAt: "2024-08-07T17:00:00Z",
			content: null,
		},
		{
			source: {
				id: "google-news",
				name: "Google News",
			},
			author: "Ars Technica",
			title: "Report: Apple’s external DVD drive is up burning discs in dongle heaven - Ars Technica",
			description: null,
			url: "https://news.google.com/rss/articles/CBMiqgFBVV95cUxOVUhPWThFRndORE5Fc3NaZlV4ekgzdFpYQVdBb0xFYzlMV0I5VUY5VGl0Z0Y1TTU2UExLTGh2UmRRVHVfMEhrVVN0enFpNW9Vckd6b3FrZV9icDhpemRpM2ZvVExOcXBHZ19icGFmZzd0MnRNZkVpXzJMd1QwS1lraHVHRnZnMHZlY1J2NENBQW9TSWtENUw4UDNySGxEV0c1R3VsYmxHYWt3QQ?oc=5",
			urlToImage: null,
			publishedAt: "2024-08-07T16:56:59Z",
			content: null,
		},
		{
			source: {
				id: "google-news",
				name: "Google News",
			},
			author: "Engadget",
			title: "Balatro is getting its first big, free gameplay update in 2025 - Engadget",
			description: null,
			url: "https://news.google.com/rss/articles/CBMirAFBVV95cUxQdS1SVXRUbV9Bc3RYc3lrc2R2WnZHQkM4bWJ3SHkxUlNJX2puSXVTTWNaT05NZkNmU3dIZjEzTkZqLVB4Y1pLUlJWOVJYdVhva2RvanI1VjE2Mktna0dXY0YtZDlXMkpZTkMyQUZObW5sU0NFTGxsSkd6cEZCWnlObFlrNlBmNllBbG96SmxkLUE2bWZVelhvV0dULU10d1ZxTlNwdFhQcHcwbGNJ?oc=5",
			urlToImage: null,
			publishedAt: "2024-08-07T16:19:38Z",
			content: null,
		},
		{
			source: {
				id: "google-news",
				name: "Google News",
			},
			author: "GameSpot",
			title: "Warhammer 40k: Space Marine 2 - All Classes PvE Co-Op Gameplay - GameSpot",
			description: null,
			url: "https://news.google.com/rss/articles/CCAiC3FiWXQtRHFlbUZZmAEB?oc=5",
			urlToImage: null,
			publishedAt: "2024-08-07T16:00:53Z",
			content: null,
		},
		{
			source: {
				id: "google-news",
				name: "Google News",
			},
			author: "EventHubs",
			title: "Terry Bogard demo and trailer confirmed coming later this month for Street Fighter 6 and here's when the party starts - EventHubs",
			description: null,
			url: "https://news.google.com/rss/articles/CBMifkFVX3lxTFBobXpOMkVmdkw4eXlxcGo5UHNwTS1mMUhWdmxUbWFMYVVsY0poWkZ2dUlUeGRvSWZCWHoxVDQ5MDFUZlBZa2dYZkpFb2Qyd0lFbzRfWXZNNHVVSWtHT0VKU2dFNTFnejE5Qkd6Wi1neDAwbmx6RV9EQndYNFZwdw?oc=5",
			urlToImage: null,
			publishedAt: "2024-08-07T15:40:38Z",
			content: null,
		},
		{
			source: {
				id: "google-news",
				name: "Google News",
			},
			author: "Forbes",
			title: "‘Helldivers 2’s Big Update Draws Negative Reviews, Doesn’t Quite Double Playercount - Forbes",
			description: null,
			url: "https://news.google.com/rss/articles/CBMiygFBVV95cUxQNFNheTBieUxmNEJZa0pIZ1NrVTlBUDhJVFJ1R1Z3eVRsQXltV2NIdkIxc0ptR21BMlNkYU5wczVkRGQzbHdxa0NHc0J3VERpV3VZb29NZ3F0N1c4NkItZWYzaWozdXFCaC1Bd2EtZWxxRjNXeDZWM3lXay1OamxmcGphSEFDYnhxeG4walNDZ3dKWHNlaC0ySzREaWZ6Tk96OHFjYnVLeE4zVnpBemtJMnhJYUhQVVpaTl9qazFxT0xCMlhYUDhXcVRR?oc=5",
			urlToImage: null,
			publishedAt: "2024-08-07T15:34:27Z",
			content: null,
		},
		{
			source: {
				id: "google-news",
				name: "Google News",
			},
			author: "Gizmodo",
			title: "Baldur's Gate 3's Latest Player Stats Reveal Who My Fellow Sickos Are - Gizmodo",
			description: null,
			url: "https://news.google.com/rss/articles/CBMilgFBVV95cUxPa2ExUFhBa0N6X285aWEtSEN4ejd4MXlhNUo1am1UZVVCdm44b0RjYW1TUmVWS1FEc1oyOUtkZzdVczVvOUxfZmczTHFtX2JBMEwzczNtazFBRDVxdlRtUDFIRnhYNWlnTlFJX0ZwVjd1MGVhdEVKdTBEZUtNUUtpT1o2SFJzcnhIZ2hfbFUySUk2enFDaWc?oc=5",
			urlToImage: null,
			publishedAt: "2024-08-07T15:32:17Z",
			content: null,
		},
	],
	science: [
		{
			source: {
				id: "google-news",
				name: "Google News",
			},
			author: "Kotaku",
			title: "Diablo IV Glitch Lets Player Gain 30+ Levels In One Second - Kotaku",
			description: null,
			url: "https://news.google.com/rss/articles/CBMiiwFBVV95cUxQZnB6dHJLajJQUjYyMzZNdVVhY1gycmtfeWU5N2ItUHNERUhaeTRCVk9vUVZTZ1BEMVdUNnRXVWF1VjYzSUpZVjZEZHRkbXNjZ1V2Wkdkb0NzQ01XZnNhRmFETjZnZXpac0hKMzFYOVNNaWVwUVFyN1VnLUhLcEN0VHFTaXp2MUpwRzJV?oc=5",
			urlToImage: null,
			publishedAt: "2024-08-07T21:40:00Z",
			content: null,
		},
		{
			source: {
				id: "google-news",
				name: "Google News",
			},
			author: "IGN",
			title: "Suicide Squad: Kill the Justice League Spurs Double-Digit Drop in WB Gaming Revenue - IGN",
			description: null,
			url: "https://news.google.com/rss/articles/CBMisAFBVV95cUxPNzl1QzlDTEhFMkxITlJ3OEJoSXYyaEVoUndzX1pUdFVOTVdiS0dBTXV4eUhiUlZoRzRuVWVUQnhNczJLQW1LNmRidjNPaU1ZQlc0NHM1QXdYc2c0NEUxak4zNElkandzNGMteGVkaXdMYS1aYnl0TlVXTnhQVkpNbU15SXFzWEVIelpKeXJYRzdkTXVkaUlCaXNFRndzVDdYTkYwM0JQZ1VSd0ZDY29Udw?oc=5",
			urlToImage: null,
			publishedAt: "2024-08-07T21:11:28Z",
			content: null,
		},
		{
			source: {
				id: "google-news",
				name: "Google News",
			},
			author: "The Verge",
			title: "Sonos delays two new products as it races to fix buggy app - The Verge",
			description: null,
			url: "https://news.google.com/rss/articles/CBMikwFBVV95cUxPbHlSUDJqYjhrWmpnWHlxbjFpM0k3MlNRWTRLOFVkMEV4ZU42YlZmYTkzZXRyS2tmeDk5UHd4R3ExVFpMNDhnUFVhek13TVpsU19seXp4SU1IWXlxMDVqWEF1N09CaHpJbnJjTzlaZzBTMHhLRjlBd0FOZWRhcm5uQ2RHZTcwNXN6VDk3bmNQdUwwNk0?oc=5",
			urlToImage: null,
			publishedAt: "2024-08-07T20:33:13Z",
			content: null,
		},
		{
			source: {
				id: "google-news",
				name: "Google News",
			},
			author: "9to5Google",
			title: "The Google TV Streamer still supports external storage - 9to5Google",
			description: null,
			url: "https://news.google.com/rss/articles/CBMiekFVX3lxTE9TclZOcFVVZGdUcW9zNHQ0ZzltUVpGbFFIaEdfREo4b2FGbG5vcmQ4MFZEc0dpYWFRZmF6RUlfRkY4dUpxSXJDcXpOa3NqU3U5aFFjYWtNOTNXeVBtNGdyc1liTXlFTkxncmVSV3JXWmZ0TGhuMVFVbVd3?oc=5",
			urlToImage: null,
			publishedAt: "2024-08-07T20:30:00Z",
			content: null,
		},
		{
			source: {
				id: "google-news",
				name: "Google News",
			},
			author: "BleepingComputer",
			title: 'Windows Update downgrade attack "unpatches" fully-updated systems - BleepingComputer',
			description: null,
			url: "https://news.google.com/rss/articles/CBMisgFBVV95cUxNMXhhTDg2SGVmOHJDZjNkdHZFYVp2QnlnS1RrT1lUcjlnZWZrZEFkclAwdzQ2M1FYUGhaZ3dZbXYwVmxZdC0xNVJHMDF2TG5UdkZGX1pWVDF6N3ZmeWhjZnFNbE9oUmhEc25idW5wSTF3S3BQRXNiX2NlR2YxNlJJWUE0cXpralJ5Y3lnNE1DMlNsS1phdXYtVExfcjhSNTNSbXlObmFnT1VyLUFKSnRIa09B0gG3AUFVX3lxTE1qWXJybGM3QXhkTFFZM1NJczRBTkNVaXZXY3hhWGFWMEQ4TUs3c1dRNkF0S0YxLWJyY1ItRFdZVU96QUl0aE5URkZTamsyTjdxaGNxT0tiS2FneVN2NG9ZVzBIMFlFNEk0UUl0dlpvMlhHV0plYTJmQWhWNXVWTk9rNTBtWGgzcjZxb2pkZUZXTGFiS096Vzl1bzExbTVNVlk0TzNNaG9CN3VBRlA5Umh5N1d5TEZ1cw?oc=5",
			urlToImage: null,
			publishedAt: "2024-08-07T20:24:33Z",
			content: null,
		},
		{
			source: {
				id: "google-news",
				name: "Google News",
			},
			author: "9to5Toys",
			title: "Big-time M3 MacBook Air deals still flying! 13-inch $149 off from $850, 15-inch 16GB $249 off - 9to5Toys",
			description: null,
			url: "https://news.google.com/rss/articles/CBMihgFBVV95cUxNZGJfMUt4Uk1xV3NVcGs4NzE0NzZxd00xMVFDeXdIRUlTd0E2b3pwam5KSks3SDNlb0VUdGNyVllGM08wMklpSW9aaE5ITjJZTFIxZGFuTkprNlNlMlFSTEtYN2FGeUM0b2tvcUNIYTBIZkJRNVBEalRyS1NMNk0xeUt5WUVRd9IBhgFBVV95cUxNZGJfMUt4Uk1xV3NVcGs4NzE0NzZxd00xMVFDeXdIRUlTd0E2b3pwam5KSks3SDNlb0VUdGNyVllGM08wMklpSW9aaE5ITjJZTFIxZGFuTkprNlNlMlFSTEtYN2FGeUM0b2tvcUNIYTBIZkJRNVBEalRyS1NMNk0xeUt5WUVRdw?oc=5",
			urlToImage: null,
			publishedAt: "2024-08-07T19:55:25Z",
			content: null,
		},
		{
			source: {
				id: "google-news",
				name: "Google News",
			},
			author: "Engadget",
			title: "People are returning Humane AI Pins faster than the company can sell them - Engadget",
			description: null,
			url: "https://news.google.com/rss/articles/CBMitwFBVV95cUxNY1JITG0xVFVCVXVoLUwzbERUNmFmaEtCRmRKVTZ0OFJmWFBWcXFoMk1Xb2N6Q2xrS0daZWxiT3dEaEtKTlJVanVTVEdtdVNiVWxONFhfLXlXSFZabjBtZ2RZOEJ5WHlKc2ZIZXJPQl9sNHgtOWlKaWtMVFhqMl9CdFVDeWJYQ015dDl0TVJtYk04YzROUGNwejEycVcwXzZLREVtOW16WnF6WjgtLW5COTJra0RoZ0k?oc=5",
			urlToImage: null,
			publishedAt: "2024-08-07T19:15:23Z",
			content: null,
		},
		{
			source: {
				id: "google-news",
				name: "Google News",
			},
			author: "TechCrunch",
			title: "Made by Google 2024: How to watch Google unveil the Pixel 9, a new foldable and more - TechCrunch",
			description: null,
			url: "https://news.google.com/rss/articles/CBMiuAFBVV95cUxQYnUzQ1lndGlwUjNvYzZnb1NFMGl0aHg0QUxITWIyWDlydUp1VGdfOGNOQkJDbXRVY0MzNDVwNHo2clZXdEFzWUNHSzVlalZETjd0SGRyTnpVcmxKLVVsN1pJUHg1QXNfdHZ6TlJPN25kaTM5OXFmaXdEYlQxX29xNTJJVWptR0NCalZhenZiUjRRUWI4VDVJVURUektOcUR4cXBEUUNPOFZ4S013SzhZUllCclU3cDNW?oc=5",
			urlToImage: null,
			publishedAt: "2024-08-07T19:10:25Z",
			content: null,
		},
		{
			source: {
				id: "google-news",
				name: "Google News",
			},
			author: "The Verge",
			title: "Fortnite will bring battle pass rewards back around - The Verge",
			description: null,
			url: "https://news.google.com/rss/articles/CBMimAFBVV95cUxNZWx1MGZmbTFuU05MQUs5U3ZYdFZCVzIzUHo5ZXFqNzZOenVwNFJicllxb1pNR0t4S3ZoNVFnOFpFZ2s2Vm9qMWExQVh5aW1KVHdKMW1sWWlqT1F4am9pZ1NoQms1aW1lcWhVdWNmeGNfbloycFJPR1RHQWg5aUdxanlxNmtId2hoVDZTYkxTU1ZQd1NkZGo5dA?oc=5",
			urlToImage: null,
			publishedAt: "2024-08-07T19:03:48Z",
			content: null,
		},
		{
			source: {
				id: "google-news",
				name: "Google News",
			},
			author: "CNET",
			title: "Nab the Anker Prime 250W USB-C Charging Station for $30 at Amazon Right Now - CNET",
			description: null,
			url: "https://news.google.com/rss/articles/CBMipAFBVV95cUxOcHEyQ1hjLWZOM2dJWi04NzBkVzNKRm1mMmJDMHpJVUZVSV93REFNWTh4STE5aUF5NFdOcl9aUzVqbnFlUGtrY3JtaFVUOVhKenNHNkx3YTZRNkh1bEZJZW9fVGpiNGRNNG10OXl6RHNuVkZGeGJ5Q0RJYkJQc1dQTFozVFN2VlFuTlc5WlAzMHhoSFhIUlY2cng3dlJNVDFJYkR4Qg?oc=5",
			urlToImage: null,
			publishedAt: "2024-08-07T19:01:00Z",
			content: null,
		},
		{
			source: {
				id: "google-news",
				name: "Google News",
			},
			author: "Android Central",
			title: "Meta is closing a beloved first-party Quest studio - Android Central",
			description: null,
			url: "https://news.google.com/rss/articles/CBMiiwFBVV95cUxPZTNPckdrV3EtQkNtT25MTlV1UnRSN0N0WWFST242QVA1WTVpUTB4LVF1N1dydkFGMTFNNWNaTG5RdnVPWVNaRXNGUDJHQlZuNVpHNWJsdWpuZzJhOTZfWDVJVGxLYWNvdThYYlZoRUtGVE1qNFMwMmNNZmZsWWlnWTVnenNnNWpmTWY0?oc=5",
			urlToImage: null,
			publishedAt: "2024-08-07T18:15:03Z",
			content: null,
		},
		{
			source: {
				id: "google-news",
				name: "Google News",
			},
			author: "The Washington Post",
			title: "Think you are sick? It may be the nocebo effect. - The Washington Post",
			description: null,
			url: "https://news.google.com/rss/articles/CBMilgFBVV95cUxPUmF1NVZmZnUzQkhndS1sN09NRXFJNWY3MXJncFNJcExUSmZkUFBBQjZPejN0UWpHVE4wNTJGOHRQd3lVRS1RTUZxc283X28xWndqOWZIX0R3WUJkM0JLczR5WllFT3hJY1RGc01iR3NkLVhzZ0J5RG9sV05XOVY5R0l3YkRXeFR1bXN2dlFsa0h4SDh1VUE?oc=5",
			urlToImage: null,
			publishedAt: "2024-08-07T18:00:00Z",
			content: null,
		},
		{
			source: {
				id: "google-news",
				name: "Google News",
			},
			author: "9to5Mac",
			title: "Apple releases iOS 17.6.1 for iPhone with ‘important bug fixes’ - 9to5Mac",
			description: null,
			url: "https://news.google.com/rss/articles/CBMie0FVX3lxTE8zZkxmSnJ6M1Z1ZFNGa3JJRGRiRGFjSlRuWVFZb3dqMVYtRnJOcExQNVZVSFp4dTB0cXlZRG9FdDMtdHFOWXk4SG5aV1FqOU83UmlRdEc3dkYtZlBMTVdEWnZSdDlaRU1WT05VZ2ZqeWpsVzVtRmFKZUtUQQ?oc=5",
			urlToImage: null,
			publishedAt: "2024-08-07T17:35:00Z",
			content: null,
		},
		{
			source: {
				id: "google-news",
				name: "Google News",
			},
			author: "Nintendo Life",
			title: "Review: Natsu-Mon: 20th Century Summer Kid (Switch) - A Pleasant Vacation, If You're Patient - Nintendo Life",
			description: null,
			url: "https://news.google.com/rss/articles/CBMiiwFBVV95cUxNWG5hQTNuXzlsLWQzcFpkd25qcExfUHhCMVkxUlRDUnlOS045ZFM0Qmt2VDBMVm5UNDJUa3pQNlgyakx5NDVsMlBaelBaM1ptYkFYYWQ5ZzF2aDRYSXh0LW85ZWpPcC1PNjZYN25kdGZKVHlqTmpNRFFyYUhhd2dQLW40NnZPRkRkVThJ?oc=5",
			urlToImage: null,
			publishedAt: "2024-08-07T17:00:00Z",
			content: null,
		},
		{
			source: {
				id: "google-news",
				name: "Google News",
			},
			author: "Ars Technica",
			title: "Report: Apple’s external DVD drive is up burning discs in dongle heaven - Ars Technica",
			description: null,
			url: "https://news.google.com/rss/articles/CBMiqgFBVV95cUxOVUhPWThFRndORE5Fc3NaZlV4ekgzdFpYQVdBb0xFYzlMV0I5VUY5VGl0Z0Y1TTU2UExLTGh2UmRRVHVfMEhrVVN0enFpNW9Vckd6b3FrZV9icDhpemRpM2ZvVExOcXBHZ19icGFmZzd0MnRNZkVpXzJMd1QwS1lraHVHRnZnMHZlY1J2NENBQW9TSWtENUw4UDNySGxEV0c1R3VsYmxHYWt3QQ?oc=5",
			urlToImage: null,
			publishedAt: "2024-08-07T16:56:59Z",
			content: null,
		},
		{
			source: {
				id: "google-news",
				name: "Google News",
			},
			author: "Engadget",
			title: "Balatro is getting its first big, free gameplay update in 2025 - Engadget",
			description: null,
			url: "https://news.google.com/rss/articles/CBMirAFBVV95cUxQdS1SVXRUbV9Bc3RYc3lrc2R2WnZHQkM4bWJ3SHkxUlNJX2puSXVTTWNaT05NZkNmU3dIZjEzTkZqLVB4Y1pLUlJWOVJYdVhva2RvanI1VjE2Mktna0dXY0YtZDlXMkpZTkMyQUZObW5sU0NFTGxsSkd6cEZCWnlObFlrNlBmNllBbG96SmxkLUE2bWZVelhvV0dULU10d1ZxTlNwdFhQcHcwbGNJ?oc=5",
			urlToImage: null,
			publishedAt: "2024-08-07T16:19:38Z",
			content: null,
		},
		{
			source: {
				id: "google-news",
				name: "Google News",
			},
			author: "GameSpot",
			title: "Warhammer 40k: Space Marine 2 - All Classes PvE Co-Op Gameplay - GameSpot",
			description: null,
			url: "https://news.google.com/rss/articles/CCAiC3FiWXQtRHFlbUZZmAEB?oc=5",
			urlToImage: null,
			publishedAt: "2024-08-07T16:00:53Z",
			content: null,
		},
		{
			source: {
				id: "google-news",
				name: "Google News",
			},
			author: "EventHubs",
			title: "Terry Bogard demo and trailer confirmed coming later this month for Street Fighter 6 and here's when the party starts - EventHubs",
			description: null,
			url: "https://news.google.com/rss/articles/CBMifkFVX3lxTFBobXpOMkVmdkw4eXlxcGo5UHNwTS1mMUhWdmxUbWFMYVVsY0poWkZ2dUlUeGRvSWZCWHoxVDQ5MDFUZlBZa2dYZkpFb2Qyd0lFbzRfWXZNNHVVSWtHT0VKU2dFNTFnejE5Qkd6Wi1neDAwbmx6RV9EQndYNFZwdw?oc=5",
			urlToImage: null,
			publishedAt: "2024-08-07T15:40:38Z",
			content: null,
		},
		{
			source: {
				id: "google-news",
				name: "Google News",
			},
			author: "Forbes",
			title: "‘Helldivers 2’s Big Update Draws Negative Reviews, Doesn’t Quite Double Playercount - Forbes",
			description: null,
			url: "https://news.google.com/rss/articles/CBMiygFBVV95cUxQNFNheTBieUxmNEJZa0pIZ1NrVTlBUDhJVFJ1R1Z3eVRsQXltV2NIdkIxc0ptR21BMlNkYU5wczVkRGQzbHdxa0NHc0J3VERpV3VZb29NZ3F0N1c4NkItZWYzaWozdXFCaC1Bd2EtZWxxRjNXeDZWM3lXay1OamxmcGphSEFDYnhxeG4walNDZ3dKWHNlaC0ySzREaWZ6Tk96OHFjYnVLeE4zVnpBemtJMnhJYUhQVVpaTl9qazFxT0xCMlhYUDhXcVRR?oc=5",
			urlToImage: null,
			publishedAt: "2024-08-07T15:34:27Z",
			content: null,
		},
		{
			source: {
				id: "google-news",
				name: "Google News",
			},
			author: "Gizmodo",
			title: "Baldur's Gate 3's Latest Player Stats Reveal Who My Fellow Sickos Are - Gizmodo",
			description: null,
			url: "https://news.google.com/rss/articles/CBMilgFBVV95cUxPa2ExUFhBa0N6X285aWEtSEN4ejd4MXlhNUo1am1UZVVCdm44b0RjYW1TUmVWS1FEc1oyOUtkZzdVczVvOUxfZmczTHFtX2JBMEwzczNtazFBRDVxdlRtUDFIRnhYNWlnTlFJX0ZwVjd1MGVhdEVKdTBEZUtNUUtpT1o2SFJzcnhIZ2hfbFUySUk2enFDaWc?oc=5",
			urlToImage: null,
			publishedAt: "2024-08-07T15:32:17Z",
			content: null,
		},
	],
};

export default defaultData;
